(source "elpy" "http://jorgenschaefer.github.io/packages/")
(source gnu)
(source marmalade)
(source melpa)

(depends-on "ace-jump-mode")
(depends-on "ack")
(depends-on "auto-complete")
(depends-on "better-defaults")
(depends-on "buffer-move")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "deferred")
(depends-on "dhall-mode")
(depends-on "feature-mode")
(depends-on "find-file-in-project")
;; (depends-on "flymake-ruby")
(depends-on "framemove" :git "https://github.com/emacsmirror/framemove.git")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "idris-mode")
(depends-on "intero")
(depends-on "jsx-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "psci-mode" :git "https://github.com/ardumont/emacs-psci.git")
(depends-on "purescript-mode")
(depends-on "rainbow-delimiters")
(depends-on "ruby-mode")
(depends-on "rust-mode")
(depends-on "smex")
(depends-on "transpose-frame")
(depends-on "whole-line-or-region")
(depends-on "windresize")
(depends-on "undo-tree")
