(source "elpy" "http://jorgenschaefer.github.io/packages/")
(source gnu)
(source marmalade)
(source melpa)

(depends-on "ace-jump-mode")
(depends-on "ack")
(depends-on "autopair")
(depends-on "better-defaults")
(depends-on "find-file-in-project")
(depends-on "flymake-ruby")
(depends-on "framemove")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "powerline" :git "https://github.com/unic0rn/powerline.git")
(depends-on "ruby-mode")
(depends-on "smex")
(depends-on "whole-line-or-region")
(depends-on "windresize")
(depends-on "undo-tree")
